### ISSUE TITLE
libgfortran.so.4

### ISSUE THREAD

**Issue by Pezhvuk** [matsengrp/sumrep#10]
libgfortran.so.3 is no longer functional for the igraph package, which is kind of a "master dependency" for sumrep and its dependencies. The relevant library must be updated through `apt-get` before proceeding, as the most up to date version is libgfortran.so.4.

**Comment by javh** [comment]
Both alakazam and shazam depend on igraph, so the shazam install will require an igraph install.

**Comment by Pezhvuk** [comment]
Hi @BrandenOlson. no problem! @javh is right, it is required by Shazam and Alakazam, and I think the problem was that, for reasons that I cannot remember, libgfortran.so.3 was being used/installed for some X dependency of probably Shazam/Alakazam (I think). Though libgfortran.so.3 seemed to had been deprecated for igraph, and was causing kind of a catch-22 situation where that X dependency would build on libgfortran.so.3, and either disallowing libgfortran.so.3 to be overwritten by .so.4, or that dependency then was needed for igraph, ergo getting rid of libgfortran.so.3 would make the whole thing collapse. Ultimately, I think, I resolved the problem by narrowing down where the problem was and replacing libgfortran.so.3 by .so.4 somehow (I still occasionally get nightmares). Sorry I cannot help more specifically, my memory of it all is quite hazy at this point.

**Comment by Pezhvuk** [comment]
That could very well be. It's relatively easy to ignore a Numpy update.

**Comment by BrandenOlson** [comment]
@Pezhvuk -- Wow, sounds like quite the hassle, but glad you got it figured out. I'd be happy to put a warning of some sort in the README, but it sounds like the cause and solution are not entirely known. Perhaps I can say something like "if you encounter problems with libgfortran.so.3 or igraph during the installation of alakazam or shazam, issue #10 might help" ?

**Comment by Pezhvuk** [comment]
@BrandenOlson, That sounds like a good idea.
