### ISSUE TITLE
Looser coupling to annotaters and simulators?

### ISSUE THREAD

**Issue by williamdlees** [matsengrp/sumrep#12]
As we discussed on the recent SW WG call, it might be an idea to provide looser coupling to these underlying tools:
- make it clearer in the README that installation of partis (and other tools?) is not explicitly required to use sumrep

- support methods that take in changeo and miairr annotation formats
- perhaps create a clear separation between methods that create annotated records and those that consume them.

The main motivation for this is that many users may wish to use sumrep methods to analyse data that they have annotated themselves or have obtained pre-annotated. Annotation of live (as opposed to simulated) records from scratch is complex because of the need to take account of the underlying methods, so when handling live records it's probably a good idea for sumrep to start with a pre-annotated set.

I wrote some lightweight support for changeo format that might save a small amount of time: [changeo_functions.zip](https://github.com/matsengrp/sumrep/files/2445586/changeo_functions.zip)

**Comment by BrandenOlson** [comment]
Thanks for the input @williamdlees! I'll try to get this integrated as much as possible by the next SW-WG call.

Could you elaborate more on the functions you sent? It looks like they were derived from code that is already in sumrep: https://github.com/matsengrp/sumrep/blob/master/R/IgBlastFunctions.R. Are there particular changes in them that you would like me to incorporate?

**Comment by williamdlees** [comment]
Thanks Branden, Yes, the files are heavily derived. I just included them as an example of how decoupling could be achieved: it's pretty trivial really, but I had the code anyway for my own purposes so I thought it might be helpful.
