### ISSUE TITLE
documentation - *running* sumrep

### ISSUE THREAD

**Issue by scharch** [matsengrp/sumrep#15]
Dumb question, but how do I run sumrep? I see that there is a `compareRepertoires` function, which seems like a good place to start, but it's not clear what format of repertoire it wants as input. I see how to run partis, IGoR, and IgBLAST from within sumrep but not how to load already-generated output from those programs (or, say, from SONAR) as a ChangeO or AIRR-formatted tab file.

tl;dr - adding some 'quick start' info to the readme would be very helpful

thanks

**Comment by BrandenOlson** [comment]
@scharch -- sorry for the confusion! I actually just added a "Usage" section to the README. Take a look and let me know if there are any further questions you have. sumrep is currently undergoing a wealth of documentation and standardization updates so please let me know if anything is unclear, and thanks for the patience.
