### ISSUE TITLE
Error: `data` must be uniquely named but has duplicate elements

### ISSUE THREAD

**Issue by Pezhvuk** [matsengrp/sumrep#28]
Hi Branden,

Calling `getVDinsertionLengthDistribution` on some files seem to return this error:

`Error: "data" must be uniquely named but has duplicate elements`

**Comment by BrandenOlson** [comment]
It seems from some googling that this can arise due to a duplicate column name. Any chance your datasets have more than one `np1_length` column?

**Comment by Pezhvuk** [comment]
Indeed, that much is clear. However, I'm only passing the `getPartisAnnotations$annotations` to `getVDinsertionLengthDistribution`. So, if there is a duplicate column in the annotations, it must be an internal error with `getPartisAnnotations`, or some other downstream process, I presume.

**Comment by BrandenOlson** [comment]
Have you verified that there are more than one `np1_length` columns in the `getPartisAnnotations$annotations` object?

**Comment by Pezhvuk** [comment]
I have not, but this is only an issue with some files, while the others are fine. So, I don't understand why some `getPartisAnnotations$annotations` would have duplicates, and not all, or _vice versa_.

**Comment by Pezhvuk** [comment]
Updating Partis to latest version solved this issue.
