### ISSUE TITLE
compareRepertoires documentation needs to be updated

### ISSUE THREAD

**Issue by scharch** [matsengrp/sumrep#40]
It looks like the usage for `compareRepertoires` has gone from `receptor_type="BCR", chain_type="heavy"` to `locus="igh"`. However, both the example scripts and the help message still reflect the old usage.

**Comment by BrandenOlson** [comment]
Ah, this is the result of #30, which I just reopened. I'll fix this and go through the rest of the relevant documentation to see if there are other places that haven't been updated.

**Comment by BrandenOlson** [comment]
Ok @scharch, I've updated the compareRepertoires examples and docs.
