### ISSUE TITLE
Automatic divergence averaging

### ISSUE THREAD

**Issue by BrandenOlson** [matsengrp/sumrep#7]
Many of the statistic comparisons used in sumrep take a long time to run for large datasets, so we resort to the following:
* Subsample the datasets to a common number of rows (e.g. ~1/10 of the total number of rows)
* Compute the divergence of the subsampled datasets
* Return the average divergence value

Currently, we are using an ad hoc number of trials for the averaging, which typically gives reasonable results and is tuned to allow for relatively fast computation. However, it would be nice to have an automatic, principled way to determine how many trials over which to average. The obvious thing to try is a simple cumulative running average, stopping when the iterates seem to stabilize, e.g., a stopping condition of the form

|m<sub>t</sub> - m<sub>t-1</sub>| < ε

where m<sub>t</sub> is the cumulative mean for iteration _t_. One obstacle to this is that summary statistic comparisons operate on vastly different scales. For example, divergence values for gene usage are often on the order of tens or hundreds, whereas divergence values for deletion lengths can be smaller than 0.001. 

My thought is to instead consider the criterion

|1 - |m<sub>t</sub> - m<sub>t-1</sub>|/ |m<sub>t-1</sub> - m<sub>t-2</sub>|| < ε

so that the algorithm is considered to converge when consecutive differences in iterates are not very different, i.e., their ratio is very close to 1.

I ran a quick simulation study and this criterion does seem robust to scale, although it has a couple of setbacks. 

* The inherent randomness in the data generation can lead to very different iteration lengths until convergence. This can be remedied by providing the option to stop after _n_ iterations have run.
* If the algorithm settles in on a value that's not the "true" mean, the criterion can still be satisfied (akin to finding a local optimum). Perhaps this can still be considered a "stabilized" estimate.

**Comment by matsen** [comment]
Nice spec, @BrandenOlson !

I might suggest something simpler like

|m<sub>t</sub> - m<sub>t-1</sub>|/ |m<sub>t</sub>| < ε

which also seems to me to adjust for variable scale but seems less prone to funny optimization pathologies.

**Comment by BrandenOlson** [comment]
This procedure has been effectively replaced by computing the divergence of the approximate distributions via subsampling. That is, instead of computing an approximate divergence via averaging, we compute the divergence of approximate distributions via subsampling.
